#Caso esteja executando com o Autoscaling desabilitado, especifique o número de replicas
replicaCount: 1

image:
  tag: "latest"

service:
  #Para executar de forma local, altere o "type" para "NodePort"
  type: LoadBalancer
  port: 80
  cloud: aws

autoscaling:
  #Para habilitar o autoscaling, altere a variavel "enable" para "true" ("replicaCount" será ignorado)
  enabled: true
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80
  
#Configurações da instância MySQL
mysqlUrl: ${MYSQL_URL}
mysqlPort: ${MYSQL_PORT}
mysql_user: ${MYSQL_USER}
mysql_password: ${MYSQL_PASSWORD}

#Configurações do provedor de pagamentos (Mercado Pago)
payment_userId: ${PAYMENT_USER_ID}
payment_accessToken: ${PAYMENT_ACCESS_TOKEN}
payment_hostWebhook: ${PAYMENT_WEBHOOK}
aws_cognito_user_pool_id: ${AWS_COGNITO_USER_POOL_ID64}
aws_region: ${AWS_REGION}

#Configurações da instância MongoDB
mongodb_user: ${MONGODB_USER}
mongodb_password: ${MONGODB_PASSWORD}
mongodb_url: ${MONGODB_URL}