#Caso esteja executando com o Autoscaling desabilitado, especifique o número de replicas
replicaCount: 1
namespace: menuguru-product 

image:
  tag: "${VERSION}"

service:
  #Para executar de forma local, altere o "type" para "NodePort"
  type: LoadBalancer
  port: 80
  cloud: aws

autoscaling:
  #Para habilitar o autoscaling, altere a variavel "enable" para "true" ("replicaCount" será ignorado)
  enabled: true
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80
  
#Configurações da instância MySQL
mysqlUrl: ${MYSQL_URL}
mysqlPort: ${MYSQL_PORT}
mysql_user: ${MYSQL_USER}
mysql_password: ${MYSQL_PASSWORD}