spring:
  application:
    name: menuguru-product
  profiles:
    default: docker
  jackson:
    deserialization:
      fail-on-unknown-properties: true     
server:
  servlet:
    context-path: "/menuguru-products/v1"      
---
spring:
  config:
    activate:
      on-profile:
      - docker
  
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver  
    url: jdbc:mysql://${MYSQL_URL}/menuguru
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl   