apiVersion: v1
kind: Service
metadata:
  name: menuguru-product-svc
  {{ if eq .Values.service.type "LoadBalancer" }}
  {{ if eq .Values.service.cloud "aws" }}
  annotations: 
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
  {{ end }}
  {{ end }}      
spec:
  selector:
    menuguru.fiapprj.perisatto.com/name: product-service 
  type: {{ .Values.service.type }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: 8080
      {{ if eq .Values.service.type "NodePort" }}
      nodePort: 30080
      {{ end }}